// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FileExplorer': string;
  'FileExplorerEmpty': string;
  'FileExplorerIcon': string;
  'FileExplorerItem': string;
  'FileExplorerSize': string;
}
export const cssExports: CssExports;
export default cssExports;
