// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'loader': string;
  'message': string;
  'root': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
