// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'icon': string;
  'selected': string;
  'size': string;
}
export const cssExports: CssExports;
export default cssExports;
